- name: Set Hostname, Root Password, Update APT, Install OpenSSH, and Add NVMe-PC ed25519 SSH Key
  hosts: all      
  tasks:
    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: yes
    
    - name: Install OpenSSH
      ansible.builtin.apt:
        name: openssh-server
        state: present
    
    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"
    
    - name: Set root password
      ansible.builtin.user:
        name: root
        password: "{{ new_root_password | password_hash('sha512') }}"

    - name: Move existing authorized_keys to authorized_keys.old if it exists
      ansible.builtin.command:
        cmd: mv /root/.ssh/authorized_keys /root/.ssh/authorized_keys.old
      ignore_errors: yes
    
    - name: Add SSH key for root
      ansible.builtin.copy:
        src: https://raw.githubusercontent.com/fragl0s/setup-new-systems/main/NVMe-PC.ed25519
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0600'

    - name: Check if SSH CA key exists
      ansible.builtin.stat:
        path: /etc/ssh/ssh_host_ed25519_key-cert.pub
      register: ssh_cd_exists
    
    - name: Create ED25519 SSH-CA if it does not exist
      ansible.builtin.shell: 'ssh-keygen -s ssh-ca -h -I "$(hostname --fqdn)-$(date +%s)" /etc/ssh/ssh_host_ed25519_key'
      when: not ssh_cd_exists.stat.exists
